export const SNARKY_DESCRIPTIONS: Record<number, string> = {
    1: "The vegan option of starter Pokémon. It’s basically a frog with a cabbage tumor, but sure, pretend it was your first choice.",
    2: "The awkward teenage phase of a salad. It looks like it's waiting for its parents to pick it up from a party it wasn't invited to.",
    3: "A toad that accidentally swallowed a palm tree. Great for shade, terrible for conversations.",
    4: "A lizard with a severe case of heartburn. If the flame goes out, it dies, which sounds like a guilt trip waiting to happen.",
    5: "It’s just a red lizard with a bad attitude. It’s like the middle child of the fire starters—angry and forgettable.",
    6: "The reason your dad left. It's a dragon that isn't a dragon, and it dies if its tail goes out. High maintenance drama queen.",
    7: "A turtle that squirts water. It’s cute until it wets the bed. Then it’s just a plumbing issue.",
    8: "It has fluffy ears and a tail, which makes no aerodynamic sense for a water turtle. It’s trying too hard to be a furry.",
    9: "It has cannons coming out of its shell. Because nature decided turtles needed artillery support.",
    10: "A worm that looks like it was designed by a 5-year-old. It evolves into a slightly harder worm.",
    11: "A green phallic symbol that does absolutely nothing. Its only defense is 'harden', which is… suggestive.",
    12: "A butterfly that dies in a week. Don't get attached. It’s the 'Marley & Me' of bug Pokémon.",
    13: "A worm with a party hat and a stinger. It looks like a clown that kills people.",
    14: "It’s a yellow tie. That’s it. It’s a tie that hangs from a tree and waits to die.",
    15: "A bee with drills for hands. Because nature hates you and wants you to suffer.",
    16: "The pigeon of the Pokémon world. It’s everywhere, it’s annoying, and it probably poops on your car.",
    17: "It’s Pidgey with a bad haircut. It thinks it’s tough, but it’s still just a bird.",
    18: "A bird that flies at Mach 2. Which means it would technically explode if it hit a window.",
    19: "A purple rat. It’s the reason you call an exterminator, not a Pokémon trainer.",
    20: "A rat on steroids. It looks like it gnaws on drywall for fun.",
    21: "The bird you catch because you couldn't find a Pidgey. It’s angry and has a beak like a shiv.",
    22: "A bird with a long neck and a bad attitude. It looks like a vulture that got a makeover.",
    23: "It’s a snake. Spelled backwards, it’s 'Snake'. Creativity was not a priority here.",
    24: "A cobra with a face on its chest. It’s trying to be scary, but it just looks like a bad tattoo.",
    25: "The corporate mascot. It’s an electric rat that refuses to get in the ball. Overrated and overexposed.",
    26: "The one Pikachu refuses to become because it doesn't want to pay taxes and get a real job.",
    27: "A brick with claws. It curls into a ball to hide from its problems, which is relatable.",
    28: "A hedgehog that went to a punk concert once and made it its entire personality.",
    29: "A rabbit with poison spikes. It’s cute, but it will stab you if you hug it. A toxic relationship in Pokémon form.",
    30: "It’s blue and angry. It looks like a rabbit that’s been through a divorce.",
    31: "A dinosaur rabbit mom. It has boobs and armor. Biology is confused.",
    32: "The male version of the toxic rabbit. It has a horn to compensate for something.",
    33: "It’s purple and angry. It looks like a rabbit that listens to death metal.",
    34: "A kaiju rabbit dad. It breaks things and probably drinks too much beer.",
    35: "A pink alien fairy. It comes from the moon, supposedly. It’s basically a space hippie.",
    36: "It looks like a pillow that gained sentience. It hears everything, so don't talk trash about it.",
    37: "A fox with six tails. It’s cute, firey, and probably sheds everywhere.",
    38: "A fox with nine tails. It’s majestic, but it holds grudges for 1000 years. Do not cross it.",
    39: "A balloon with eyes. It sings until you fall asleep and then draws on your face. A sociopath.",
    40: "A bigger balloon. Its fur is 'sublime', which is just a fancy way of saying expensive to groom.",
    41: "A bat with no eyes. It screams at you in caves. It is the bane of every trainer's existence.",
    42: "A bat with a mouth that is 90% of its body. It drinks blood. Sleep tight.",
    43: "A weed with legs. It walks around at night screaming. It’s a plant that needs an exorcist.",
    44: "It drools nectar that smells like rotting garbage. It’s the smelly kid in class.",
    45: "A flower that smells like a corpse. It’s pretty, but you can’t bring it home to mom.",
    46: "A crab with mushrooms growing on its back. It has a fungal infection and we’re supposed to fight with it.",
    47: "The mushroom took over. The bug is dead. It’s a zombie crab controlled by a fungus. The Last of Us: Pokémon Edition.",
    48: "A purple furball with eyes. It shoots lasers from its eyes, because why not.",
    49: "A moth that scatters toxic dust. It’s a health hazard with wings.",
    50: "A thumb with a nose. It lives underground. No one knows what the rest of it looks like, and maybe we don't want to.",
    51: "Three thumbs with noses. They move in unison, which is creepy. Are they attached? We'll never know.",
    52: "A cat with a coin on its head. It loves money. It’s the capitalist of the Pokémon world.",
    53: "A fancy cat. It’s snobby and will scratch your leather sofa just to spite you.",
    54: "A duck with a migraine. It explodes with psychic energy when its head hurts. Get this bird some Advil.",
    55: "A blue duck that swims fast. It’s confused why it’s not a Psychic type. We are too.",
    56: "A monkey that is always angry. It throws poop and punches things. It has anger management issues.",
    57: "A monkey that is so angry it literally dies if it stops being angry. It’s a heart attack waiting to happen.",
    58: "A puppy that breathes fire. It’s loyal, cute, and a massive fire hazard.",
    59: "A big dog that runs fast. It’s majestic, but good luck feeding it.",
    60: "A tadpole with a swirl on its stomach. That swirl is actually its intestines. Enjoy that fact.",
    61: "A bigger tadpole with hands. It can slap you now. The intestines are still visible.",
    62: "A muscular frog. It looks like it hits the gym 8 days a week and drinks raw eggs.",
    63: "It sleeps 18 hours a day and teleports away when you try to catch it. A flake.",
    64: "It holds a spoon and has a mustache. It bends spoons with its mind. A parlor trick pony.",
    65: "It has two spoons and an IQ of 5000. It’s smarter than you and it knows it.",
    66: "A grey child that lifts weights. It’s weirdly humanoid and unsettling.",
    67: "It wears a belt to keep its power in check. Or maybe its pants up. Who knows.",
    68: "It has four arms. It can punch you four times at once. It helps with moving furniture, though.",
    69: "A plant that looks like a bell. It shoots acid. Don't put your finger in it.",
    70: "A bigger bell plant. It hangs from trees and eats bugs. It looks constantly surprised.",
    71: "A pitcher plant that eats large animals. It smells like honey but tastes like death.",
    72: "A jellyfish with angry eyes. It stings you at the beach. Everyone hates it.",
    73: "A jellyfish with 80 tentacles. It’s a floating nightmare of stinging pain.",
    74: "A rock with arms. It punches people. It’s simple, effective, and dumb as a rock.",
    75: "A boulder with four arms. It rolls down hills and crushes hikers. Nature's bowling ball.",
    76: "A turtle made of rocks. It explodes if you look at it wrong. A walking landmine.",
    77: "A horse on fire. Don't ride it unless you want third-degree burns on your inner thighs.",
    78: "A unicorn on fire. It runs fast and looks cool, but it’s still a fire hazard.",
    79: "A pink thing that is slow and dumb. It fishes with its tail and forgets what it’s doing.",
    80: "The pink thing got bit on the butt by a shell and now it’s a genius? Evolution is weird.",
    81: "A magnet with an eye. It sticks to your fridge and erases your credit cards.",
    82: "Three magnets stuck together. The creativity budget ran out here.",
    83: "A duck holding a leek. It tastes delicious, apparently. It comes with its own garnish.",
    84: "A bird with two heads. They argue with each other. It’s a walking identity crisis.",
    85: "A bird with three heads. One represents joy, one sorrow, and one anger. It’s a mood swing with wings.",
    86: "A seal with a horn. It lives in ice. It’s cute but smells like fish.",
    87: "A dugong. It’s majestic and white. Sailors used to think these were mermaids. Sailors were lonely.",
    88: "A pile of purple sludge. It was created by pollution. Thanks, humanity.",
    89: "A bigger pile of sludge. It smells so bad it kills plants just by existing.",
    90: "A clam with a tongue. It clamps onto things and never lets go. Like a needy ex.",
    91: "A clam with a spike. Its shell is harder than diamond. It’s basically a tank.",
    92: "A ball of gas with a face. It suffocates its prey. A literal toxic fart.",
    93: "A ghost with disembodied hands. It licks you to steal your life force. Kinky?",
    94: "A shadow with a smile. It hides in your shadow and waits to kill you. Sleep tight.",
    95: "A giant rock snake. It burrows underground at 50mph. It’s terrifyingly fast for a rock.",
    96: "A tapir that eats dreams. If you have a nightmare, it’s because this thing didn't eat it.",
    97: "It carries a pendulum and hypnotizes children. Stranger danger: The Pokémon.",
    98: "A crab. It has claws. It pinches. That’s about it.",
    99: "A crab with one giant claw. It looks like it’s been working out only one arm. We know why.",
    100: "A ball that looks like a Poké Ball. It explodes. It’s a mimic that hates you.",
    101: "An upside-down ball. It explodes faster. It loves to self-destruct.",
    102: "Six eggs. One of them is cracked and shows a brain. Are they seeds? Eggs? Who knows.",
    103: "A walking palm tree with three faces. Each face has its own mind. A committee of idiots.",
    104: "It wears the skull of its dead mother. It cries at the moon. The most goth Pokémon ever.",
    105: "The orphan grew up and got a bone club. It’s aggressive and has abandonment issues.",
    106: "A kickboxing blob with legs. It has no head, just eyes on its chest. Anatomy is optional.",
    107: "A boxer in a dress. It punches faster than the eye can see. Don't make fun of the skirt.",
    108: "A pink blob with a giant tongue. It licks everything. It’s gross and sticky.",
    109: "A floating gas mine. It looks like a virus. It explodes if you get too close.",
    110: "Two gas mines stuck together. One looks miserable. Being a conjoined twin made of poison sucks.",
    111: "A rock rhino. It has a tiny brain and runs in straight lines. It crashes into things constantly.",
    112: "A bipedal rock rhino. It can withstand lava. It’s tough but not smart.",
    113: "An egg nurse. It carries an egg in a pouch. It’s basically a walking omelette station.",
    114: "A vine monster with shoes. No one knows what it looks like under the vines. Probably disappointing.",
    115: "A mom kangaroo with a baby. The baby is never seen leaving the pouch. Failure to launch.",
    116: "A seahorse. It shoots ink. It’s cute and harmless unless you're a small shrimp.",
    117: "A spiky seahorse. It’s poisonous. Don't touch it.",
    118: "A goldfish with a horn. It’s elegant but useless out of water.",
    119: "A fish with a horn. It’s slightly more aggressive. Still just a fish.",
    120: "A starfish with a jewel. It regenerates limbs. It’s an alien, probably.",
    121: "Two starfish glued together. It spins like a propeller and shoots water. It’s a geometric nightmare.",
    122: "A clown mime. It creates invisible walls. It’s creepy and hangs out with moms.",
    123: "A mantis with scythes for arms. It’s a ninja bug. It hates the color red.",
    124: "A lady in a dress that kisses people to freeze them. It speaks a language that sounds like human speech.",
    125: "A yellow electric tiger man. It spins its arms to generate power. It causes blackouts.",
    126: "A duck with a butt on its head. It lives in volcanoes. It’s made of fire.",
    127: "A stag beetle with a vice grip on its head. It breaks trees in half. It hates the cold.",
    128: "A bull with three tails. It whips itself to get angry. A masochist.",
    129: "A useless fish. It splashes. It does nothing. It is a disappointment to its family.",
    130: "The useless fish got angry and became a sea dragon. It destroys cities for fun.",
    131: "A Loch Ness monster. It ferries people across the sea. It’s gentle and endangered.",
    132: "A purple blob. It can transform into anything. It’s used for... breeding. A lot.",
    133: "A generic dog/fox/cat thing. It has unstable DNA. It can become anything depending on the rock you throw at it.",
    134: "The water dog. It melts into water. It’s basically a puddle with ears.",
    135: "The electric dog. It’s spiky and agitated. It’s like petting a live wire.",
    136: "The fire dog. It’s fluffy and warm. It stores heat in its body. A living hot water bottle.",
    137: "A digital duck. It’s made of code. It can enter cyberspace. Don't check its browser history.",
    138: "A fossil snail. It was resurrected from a rock. It has tentacles. Praise Helix.",
    139: "A spiky fossil snail. It has a beak that can crush bone. It’s a prehistoric nightmare.",
    140: "A fossil horseshoe crab. It has eyes on its back. It watches you while it sleeps.",
    141: "A fossil slasher. It has scythes for hands. It swims fast and cuts prey in half.",
    142: "A fossil pterodactyl. It flies and screams. It’s a dinosaur with an attitude.",
    143: "A fat bear that sleeps and eats. It blocks roads. It is my spirit animal.",
    144: "An ice bird. It’s legendary and cold. It freezes moisture in the air to make snow.",
    145: "An electric bird. It’s spiky and loud. It lives in thunderstorms.",
    146: "A fire bird. It’s on fire. It represents spring, apparently.",
    147: "A blue worm. It sheds its skin. It’s rare and hard to find.",
    148: "A blue snake with wings on its head. It controls the weather. It’s elegant.",
    149: "An orange dragon with tiny wings. It’s friendly and saves drowning sailors. The Moomin of dragons.",
    150: "A genetic experiment gone wrong. It hates humanity. It lives in a cave and broods.",
    151: "The ancestor of all Pokémon. It’s pink and floats. It hides under a truck.",
    152: "A leaf dinosaur. It has a leaf on its head. It smells like herbs.",
    153: "A bigger leaf dinosaur. It has a necklace of buds. It smells spicy.",
    154: "A flower dinosaur. It breathes to revive dead grass. A walking air freshener.",
    155: "A fire mouse. It has fire on its back. It’s timid but burns hot.",
    156: "A fire weasel. It has a mohawk of fire. It’s agile and burns things.",
    157: "A fire badger. It has a volcano on its neck. It rubs its fur together to cause explosions.",
    158: "A blue crocodile. It bites everything. It’s hyperactive.",
    159: "A caveman crocodile. It wears a skin pattern like a toga. It’s getting older.",
    160: "A big blue alligator. It runs on two legs. It’s terrifyingly fast on land.",
    161: "A scout squirrel. It stands on its tail to look around. It’s paranoid.",
    162: "A long squirrel. It’s very long. It can corner like a drift car.",
    163: "An owl with one leg. It has an internal clock. It’s always judging you.",
    164: "A wise owl. It thinks deep thoughts. It’s smarter than your average bird.",
    165: "A ladybug with fists. It punches things. It’s surprisingly aggressive.",
    166: "A ladybug alien. It uses starlight to power up. It’s a Power Ranger.",
    167: "A green spider with a face on its back. The face changes when it's angry.",
    168: "A red spider. It spins webs from its butt and its mouth. Efficient.",
    169: "A bat with four wings. It flies silently. It bites you without you knowing.",
    170: "A fish with a lightbulb. It lives in the deep sea. It zaps prey.",
    171: "A dolphin with a lightbulb. It’s friendly but will electrocute you by accident.",
    172: "A baby Pikachu. It can't control its electricity and shocks itself. A liability.",
    173: "A baby star. It looks like a marshmallow. It’s useless in battle.",
    174: "A baby balloon. It bounces around. It has red eyes that stare into your soul.",
    175: "An egg with a head. It brings happiness, allegedly. It mostly just cries.",
    176: "A fairy egg. It flies with tiny wings. It spreads joy dust.",
    177: "A tiny bird. It hops around. It can see the future but can't change it.",
    178: "A totem pole bird. It sees the past and future simultaneously. It is paralyzed by existential dread.",
    179: "A sheep with static wool. It shocks you if you pet it. A forbidden pillow.",
    180: "A pink sheep. It stands on two legs. Its wool is rubbery.",
    181: "A lighthouse dragon. It has a light on its tail. It guides ships and looks fabulous.",
    182: "A hula dancer flower. It dances in the sun. It smells nice but has no attacks.",
    183: "A water mouse. Its tail is a float. It never drowns.",
    184: "A water rabbit. It has long ears. It plays in rivers and drowns unsuspecting swimmers.",
    185: "A rock that looks like a tree. It hates water. It’s a mimic that fails at mimicry.",
    186: "A green frog with a hair curl. It claps its hands and summons rain. A weather wizard.",
    187: "A dandelion cat. It floats in the wind. It has no control over its life.",
    188: "A flower cat. It blooms in the sun. It’s happy as long as it’s warm.",
    189: "A cotton ball cat. It rides the wind across the ocean. It spreads spores everywhere.",
    190: "A monkey with a hand on its tail. It’s mischievous and steals your keys.",
    191: "A seed. It is the weakest Pokémon in existence. It falls from the sky and does nothing.",
    192: "A sunflower. It moves its face to follow the sun. It’s creepy at night.",
    193: "A dragonfly. It flies fast and sees everything. It’s a drone with wings.",
    194: "A water axolotl. It has no arms. It smiles while it suffers.",
    195: "A water salamander. It’s slippery and dumb. It bumps into rocks and doesn't care.",
    196: "A psychic cat. It predicts the future by reading air currents. It’s elegant and judgmental.",
    197: "A dark cat. It glows in the dark. It sweats poison when it's agitated. Don't stress it out.",
    198: "A crow with a hat. It steals shiny things. It’s a mob boss.",
    199: "A slow hippo with a shell hat. It’s a genius now. It rules the beach.",
    200: "A ghost head. It screams to scare people. It feeds on fear.",
    201: "Alphabet soup. There are 28 versions of this useless letter. Collect them all, or don't.",
    202: "A blue blob with a tail. The tail is the real body. It hits itself to endure pain.",
    203: "A giraffe with a tail that bites. The tail has a brain. It watches you while you sleep.",
    204: "A pinecone. It hangs from trees and explodes. It’s a grenade with eyes.",
    205: "A bagworm in a steel shell. It shoots spikes. It’s a fortress.",
    206: "A land snake with wings. It digs with its tail. It’s rare and weird.",
    207: "A flying scorpion. It glides on the wind. It clamps onto your face.",
    208: "A steel snake. It chews through mountains. Its teeth are harder than diamond.",
    209: "A pink bulldog. It looks scary but is actually a coward. It runs away from chihuahuas.",
    210: "A purple bulldog. It’s timid but has a strong jaw. It’s a good guard dog if it doesn't faint.",
    211: "A pufferfish. It shoots toxic needles. It’s a floating mine.",
    212: "A red metal mantis. It has claws that crush steel. It’s cooler than you.",
    213: "A moldy rock turtle. It ferments berries in its shell. It makes moonshine.",
    214: "A giant beetle. It flips tanks. It loves honey and fighting.",
    215: "A weasel with claws. It steals eggs. It’s a thief and a vandal.",
    216: "A teddy bear with a moon. It’s cute but licks honey off its paws which are soaked in it.",
    217: "A bear with a sun. It snaps trees in half. It’s angry and hungry.",
    218: "A lava slug. It never sleeps. If it stops moving, it hardens and dies.",
    219: "A lava snail. Its shell is made of hardened magma. It’s brittle.",
    220: "A pig with fur. It smells mushrooms. It’s a truffle pig.",
    221: "A boar with fur. Its hair covers its eyes. It charges blindly.",
    222: "A coral reef. It grows on its head. It sheds branches as gifts.",
    223: "A fish that looks like a gun. It shoots water with sniper accuracy.",
    224: "An octopus tank. It shoots ink and rocks. It’s heavy artillery.",
    225: "A Santa penguin. It gives presents that explode. It’s a troll.",
    226: "A kite ray. It swims calmly. It lets fish clean its leftovers.",
    227: "A steel bird. Its feathers are swords. It flies at 180mph.",
    228: "A dark dog. It hunts in packs. It uses teamwork to kill.",
    229: "A hellhound. Its fire burns forever. If you get burned, it hurts for life.",
    230: "A sea dragon. It creates whirlpools. It sleeps deep in the ocean.",
    231: "A tiny elephant. It’s strong for its size. It plays in the mud.",
    232: "A tire elephant. It rolls into a ball and flattens cars. It’s armor-plated.",
    233: "A digital duck upgrade. It’s smoother and smarter. It explores space.",
    234: "A deer with an eye on its butt. It creates illusions. It stares into your soul.",
    235: "A painter dog. It paints with its tail. Its art expresses its feelings.",
    236: "A fighting kid. It has potential to be three different things. No pressure.",
    237: "A spinning top man. It kicks while spinning. It gets dizzy.",
    238: "A kissing baby. It kisses everything. It’s weirdly affectionate.",
    239: "A plug baby. It spins its arms to generate electricity. It’s a living generator.",
    240: "A fire baby. It spits embers. It’s a fire hazard in a diaper.",
    241: "A cow. It produces milk. It rolls around. It’s a tank.",
    242: "A nurse egg. It has the highest HP. It takes hits and smiles.",
    243: "A thunder tiger. It carries a storm on its back. It barks thunder.",
    244: "A volcano lion. It barks magma. It represents the pressure of the earth.",
    245: "A water leopard. It purifies water. It runs on the wind.",
    246: "A rock skin baby. It eats dirt to grow. It lives deep underground.",
    247: "A rock shell. It’s waiting to evolve. It has a temper.",
    248: "A Godzilla. It destroys mountains. It is invincible.",
    249: "A sea guardian. It suppresses storms. It lives in a trench.",
    250: "A rainbow bird. It resurrects the dead. It flies continuously.",
    251: "A forest fairy. It travels through time. It brings lush forests.",
    252: "A gecko with a twig. It’s cool and collected. It climbs walls.",
    253: "A gecko with leaves. It jumps fast. It’s agile.",
    254: "A gecko with a tree on its tail. It grows seeds on its back. It’s a jungle warrior.",
    255: "A fire chick. It’s warm to hold. It has a fire inside.",
    256: "A fire chicken. It kicks things. It’s getting aggressive.",
    257: "A fire fighting chicken. It jumps over buildings. It kicks with fire.",
    258: "A mud fish. It has a fin on its head. It’s sturdy.",
    259: "A mud fish with legs. It plays in the mud. It’s happy.",
    260: "A mud monster. It drags boulders. It swims faster than a jet ski.",
    261: "A dark dog. It bites everything. It’s tenacious.",
    262: "A dark wolf. It hunts in packs. It obeys orders.",
    263: "A raccoon. It walks in zigzags. It’s curious.",
    264: "A badger. It runs in straight lines. It tackles everything.",
    265: "A worm. It eats leaves. It’s waiting to change.",
    266: "A white cocoon. It hangs from branches. It waits.",
    267: "A butterfly. It drinks nectar. It’s colorful.",
    268: "A purple cocoon. It’s hard. It waits.",
    269: "A moth. It scatters dust. It’s attracted to light.",
    270: "A lily pad. It floats on water. It carries small Pokémon.",
    271: "A kappa. It plays pranks. It loves music.",
    272: "A pineapple duck. It dances to music. It’s always happy.",
    273: "A acorn. It hangs from trees. It looks like a nut.",
    274: "A leaf goblin. It plays a flute. It lives in forests.",
    275: "A leaf tengu. It creates wind storms. It guards forests.",
    276: "A swallow. It’s brave. It stands up to big foes.",
    277: "A big swallow. It dives at prey. It’s fast.",
    278: "A seagull. It carries food in its beak. It floats on updrafts.",
    279: "A pelican. It carries things in its mouth. It’s a courier.",
    280: "A feeling Pokémon. It senses emotions. It hides from negativity.",
    281: "A dancer. It spins on tiptoes. It senses feelings.",
    282: "A guardian angel. It protects its trainer. It creates black holes.",
    283: "A pond skater. It slides on water. It secretes oil.",
    284: "A moth with eye patterns. It scares predators. It flies in rain.",
    285: "A mushroom. It scatters spores. It’s grumpy.",
    286: "A boxing mushroom. It has stretchy arms. It punches fast.",
    287: "A sloth. It sleeps all day. It eats 3 leaves.",
    288: "A monkey. It can't sit still. It runs wild.",
    289: "A giant sloth. It’s lazy again. It hits like a truck.",
    290: "A cicada nymph. It lives underground. It waits.",
    291: "A cicada. It moves fast. It buzzes loud.",
    292: "A ghost shell. It steals souls. Don't look in the hole.",
    293: "A whisper. It cries loud. It hears everything.",
    294: "A loud speaker. It shouts to attack. It has big ears.",
    295: "A boombox. It creates earthquakes with sound. It roars.",
    296: "A sumo trainee. It trains hard. It eats a lot.",
    297: "A sumo master. It slaps hard. It stops trains.",
    298: "A blue mouse. It bounces on its tail. It’s sad.",
    299: "A nose compass. It always points north. It can't turn.",
    300: "A kitten. It chases its tail. It’s cute.",
    301: "A cat lady. It’s elegant. It hates dirt.",
    302: "A gem eater. It has gems for eyes. It lives in caves.",
    303: "A mouth head. It deceives prey. It bites hard.",
    304: "A metal eater. It eats iron ore. It makes armor.",
    305: "A metal beast. It eats trucks. It clashes for territory.",
    306: "A metal monster. It claims a mountain. It destroys environments.",
    307: "A meditator. It eats one berry a day. It floats.",
    308: "A yoga master. It senses auras. It dances in battle.",
    309: "A static dog. It stores electricity in fur. It runs fast.",
    310: "A lightning dog. It creates thunder clouds. It discharges power.",
    311: "A plus mouse. It cheers for friends. It sparks.",
    312: "A minus mouse. It cheers for partners. It sparks.",
    313: "A firefly. It uses light to signal. It loves sweet scents.",
    314: "A firefly lady. It guides the swarm. It draws patterns.",
    315: "A rose lady. It has poison thorns. It smells sweet.",
    316: "A stomach. It eats everything. It digests scrap metal.",
    317: "A poison bag. It swallows things whole. It has no teeth.",
    318: "A piranha. It has rough skin. It bites boats.",
    319: "A shark torpedo. It swims fast. It breaks hulls.",
    320: "A ball whale. It bounces on beaches. It drinks tons of water.",
    321: "A giant whale. It is the biggest. It eats schools of fish.",
    322: "A camel. It stores magma. It’s slow.",
    323: "A volcano camel. It erupts when angry. It has craters.",
    324: "A coal turtle. It burns coal inside. It smokes.",
    325: "A spring pig. It bounces. If it stops, it dies.",
    326: "A pig dancer. It controls pearls. It dances oddly.",
    327: "A dizzy bear. It has unique spots. It stumbles.",
    328: "A pit digger. It waits in a hole. It has big jaws.",
    329: "A dragon fly. It vibrates wings. It causes headaches.",
    330: "A desert spirit. It creates sandstorms. It sings.",
    331: "A cactus ball. It lives in deserts. It has a flower.",
    332: "A scarecrow. It hunts at night. It stalks travelers.",
    333: "A cotton bird. It likes to clean. It sits on heads.",
    334: "A cloud bird. It sings soprano. It flies in clouds.",
    335: "A mongoose. It fights snakes. It has claws.",
    336: "A snake. It fights mongooses. It has a knife tail.",
    337: "A moon rock. It floats. It glows at night.",
    338: "A sun rock. It spins. It glows in the day.",
    339: "A whisker fish. It senses quakes. It’s slimy.",
    340: "A catfish. It causes quakes. It eats anything.",
    341: "A crab. It was a pet. It adapted to the wild.",
    342: "A rogue crab. It destroys ponds. It’s violent.",
    343: "A clay doll. It spins on one leg. It was made by ancients.",
    344: "A clay idol. It floats. It shoots beams.",
    345: "A sea lily. It was extinct. It anchors to rocks.",
    346: "A barnacle plant. It melts prey. It lives in shallows.",
    347: "A shrimp fossil. It swims with wings. It has claws.",
    348: "A armor shrimp. It has plate armor. It hunts on land.",
    349: "A ugly fish. It eats anything. It’s hardy.",
    350: "A beautiful serpent. It calms anger. It’s a muse.",
    351: "A weather ball. It changes with weather. It’s small.",
    352: "A chameleon. It blends in. It has a zigzag stripe.",
    353: "A ghost doll. It feeds on envy. It seeks its owner.",
    354: "A zipper doll. It holds a grudge. It was thrown away.",
    355: "A skull ghost. It loves crying children. It passes through walls.",
    356: "A mummy ghost. It has a black hole inside. It waves its hands.",
    357: "A banana dinosaur. It flies with leaves. It gives fruit.",
    358: "A wind chime. It floats in wind. It makes sounds.",
    359: "A disaster dog. It warns of danger. It is misunderstood.",
    360: "A patient blob. It endures attacks. It has a tail eye.",
    361: "A snow hat. It shivers. It eats snow.",
    362: "A hockey mask. It freezes moisture. It has a rock body.",
    363: "A seal ball. It rolls on ice. It claps.",
    364: "A seal. It balances balls. It has whiskers.",
    365: "A walrus. It breaks ice. It has thick blubber.",
    366: "A pearl clam. It lives in the deep. It makes pearls.",
    367: "A eel. It lives in the deep. It hunts clams.",
    368: "A fish. It has a map on its scales. It lives long.",
    369: "A rock map. It has no brain. It’s a living fossil.",
    370: "A heart fish. It swims in schools. It jumps.",
    371: "A dragon head. It wants to fly. It jumps off cliffs.",
    372: "A shell dragon. It rolls fast. It protects its body.",
    373: "A salamence. It flies finally. It burns fields.",
    374: "A robot eye. It floats. It calculates.",
    375: "A robot crab. It has four legs. It thinks fast.",
    376: "A super computer. It has four legs. It rivals humans.",
    377: "A rock golem. It guards caves. It solves puzzles.",
    378: "A ice golem. It stays frozen. It breaks easily.",
    379: "A steel golem. It is flexible. It is unknown metal.",
    380: "A jet dragon. It flies fast. It has a sister.",
    381: "A jet dragon. It flies fast. It has a brother.",
    382: "A rain god. It expands oceans. It sleeps.",
    383: "A sun god. It expands land. It sleeps.",
    384: "A sky god. It stops fights. It lives in ozone.",
    385: "A wish maker. It sleeps 1000 years. It has an eye.",
    386: "A virus alien. It changes forms. It attacks.",
    387: "A turtle with a twig. It’s shy. It lives near lakes.",
    388: "A bush turtle. It knows where springs are. It carries a shell.",
    389: "A continent turtle. It carries a small world. It doesn't move.",
    390: "A fire monkey. It climbs cliffs. It has a butt flame.",
    391: "A fighting monkey. It has a long tail. It uses martial arts.",
    392: "A monkey king. It has fire hair. It fights fast.",
    393: "A penguin. It’s proud. It hates being touched.",
    394: "A prince penguin. It lives alone. It has strong wings.",
    395: "A emperor penguin. It leads the pack. It swims fast.",
    396: "A bird. It flies well. It mimics cries.",
    397: "A hawk. It has claws. It grooms itself.",
    398: "A raptor. It has a crest. It intimidates.",
    399: "A beaver. It gnaws logs. It builds dams.",
    400: "A worker beaver. It carries things. It’s dull.",
    401: "A cricket. It sings. It has a hard shell.",
    402: "A violin cricket. It plays melodies. It uses knife arms.",
    403: "A spark lion. It flashes light. It rivals others.",
    404: "A x-ray lion. It sees through walls. It hunts.",
    405: "A x-ray lion king. It sees everything. It leads.",
    406: "A bud. It likes clean water. It is sensitive.",
    407: "A bouquet. It attracts prey. It has thorns.",
    408: "A fossil. It has a hard skull. It headbutts.",
    409: "A rampardos. It smashes things. It has a thick skull.",
    410: "A shield fossil. It has a face shield. It protects.",
    411: "A bastion. It blocks attacks. It is a wall.",
    412: "A bagworm. It makes a cloak. It evolves differently.",
    413: "A trash cloak. It uses trash. It adapts.",
    414: "A moth. It loves honey. It protects the hive.",
    415: "A bee queen. It commands the hive. It fights.",
    416: "A bee. It gathers honey. It serves the queen.",
    417: "A squirrel. It stores electricity. It runs fast.",
    418: "A weasel. It floats. It has two tails.",
    419: "A float weasel. It rescues people. It swims fast.",
    420: "A cherry. It is small. It is tasty.",
    421: "A flower. It opens in sun. It is positive.",
    422: "A slug. It lives in mud. It is soft.",
    423: "A sea slug. It has three heads. It lives in mud.",
    424: "A monkey. It has a hand tail. It jumps.",
    425: "A balloon. It drifts. It carries souls.",
    426: "A blimp. It carries people. It vanishes.",
    427: "A bunny. It has fluff. It kicks.",
    428: "A lop bunny. It is elegant. It fights.",
    429: "A ghost. It screams. It scares people.",
    430: "A crow boss. It leads the flock. It is smart.",
    431: "A cat. It is sleek. It hypnotizes.",
    432: "A fat cat. It is ugly. It binds prey.",
    433: "A bell. It rings. It floats.",
    434: "A skunk. It smells. It sprays.",
    435: "A tank skunk. It sprays far. It smells bad.",
    436: "A mirror. It reflects. It is steel.",
    437: "A bell. It heals. It floats.",
    438: "A rock baby. It cries. It mimics.",
    439: "A mime baby. It mimics. It is cute.",
    440: "A egg. It carries a stone. It is happy.",
    441: "A note. It mimics speech. It flies.",
    442: "A stone. It has a soul. It is forbidden.",
    443: "A land shark. It digs. It bites.",
    444: "A shark. It flies. It hunts.",
    445: "A jet shark. It flies fast. It hunts.",
    446: "A munchlax. It eats. It sleeps.",
    447: "A riolu. It senses aura. It runs.",
    448: "A lucario. It fights. It reads minds.",
    449: "A hippo. It lives in sand. It sweats sand.",
    450: "A hippo king. It is angry. It creates storms.",
    451: "A scorpion. It has claws. It poisons.",
    452: "A ogre scorpion. It crushes. It poisons.",
    453: "A frog. It fights. It has poison sacs.",
    454: "A toxic frog. It fights dirty. It stabs.",
    455: "A plant. It eats bugs. It floats.",
    456: "A fish. It has fins. It glows.",
    457: "A neon fish. It glows deep. It swims.",
    458: "A mantyke. It swims. It jumps.",
    459: "A tree. It creates snow. It is cold.",
    460: "A obama. It creates blizzards. It is big.",
    461: "A weavile. It hunts in packs. It is fast.",
    462: "A magnet. It has three eyes. It floats.",
    463: "A tongue. It licks. It is pink.",
    464: "A rhyperior. It shoots rocks. It is heavy.",
    465: "A vine. It grows arms. It grabs.",
    466: "A electivire. It punches. It shocks.",
    467: "A magmortar. It shoots fire. It burns.",
    468: "A togekiss. It flies. It blesses.",
    469: "A yanmega. It flies fast. It bites.",
    470: "A leafeon. It uses photosynthesis. It is calm.",
    471: "A glaceon. It freezes air. It is cold.",
    472: "A gliscor. It glides. It bites.",
    473: "A mamoswine. It charges. It is ancient.",
    474: "A porygon z. It glitches. It is weird.",
    475: "A gallade. It fights. It has blades.",
    476: "A nosepass. It points north. It has a mustache.",
    477: "A dusknoir. It takes souls. It has a mouth.",
    478: "A froslass. It freezes prey. It is a ghost.",
    479: "A rotom. It possesses electronics. It pranks.",
    480: "A uxie. It knows all. It sleeps.",
    481: "A mesprit. It feels all. It plays.",
    482: "A azelf. It wills all. It fights.",
    483: "A dialga. It controls time. It roars.",
    484: "A palkia. It controls space. It roars.",
    485: "A heatran. It crawls on ceilings. It melts.",
    486: "A regigigas. It pulls continents. It is slow.",
    487: "A giratina. It lives in distortion. It is a ghost.",
    488: "A cresselia. It gives dreams. It flies.",
    489: "A phione. It drifts. It is rare.",
    490: "A manaphy. It bonds. It swims.",
    491: "A darkrai. It gives nightmares. It hides.",
    492: "A shaymin. It cleans air. It flies.",
    493: "A arceus. It created all. It is god.",
    494: "A victini. It wins. It brings luck.",
    495: "A snivy. It is smug. It uses vines.",
    496: "A servine. It is fast. It uses vines.",
    497: "A serperior. It glares. It stops foes.",
    498: "A tepig. It shoots fire. It eats berries.",
    499: "A pignite. It fights. It gets fat.",
    500: "A emboar. It has a beard of fire. It punches."
};
