export const SNARKY_DESCRIPTIONS: Record<number, string> = {
    1: "The vegan option. It’s a frog with a garlic bulb on its back. It tries its best, but we all know you wanted Charmander.",
    2: "The awkward teenage phase. It looks like a salad that got angry. It’s waiting for its flower to bloom so it can finally be popular.",
    3: "A toad that swallowed a palm tree. It’s huge, it’s grumpy, and it probably smells like swamp water and regret.",
    4: "A lizard with a severe anxiety disorder. If the flame on its tail goes out, it dies. No pressure, though.",
    5: "It’s red now. It’s angrier. It’s basically a teenager with a lighter and a bad attitude.",
    6: "The dragon that isn't a dragon. It’s the reason your dad left. High maintenance, overrated, and dies to a pebble.",
    7: "A turtle that squirts water. It’s cute until it wets the carpet. Then it’s just a plumbing issue.",
    8: "It has fluffy ears and a tail, which makes no aerodynamic sense for a water turtle. It’s trying too hard to be a furry.",
    9: "It has literal cannons on its back. Because nature decided turtles needed artillery support. American turtle.",
    10: "A worm. It eats leaves. It does nothing. It’s the participation trophy of Pokémon.",
    11: "A green phallic symbol that only knows 'Harden'. We’re not touching that joke. It writes itself.",
    12: "A butterfly that dies in a week. Don't get attached. It’s the 'Marley & Me' of bug Pokémon.",
    13: "A worm with a party hat and a stinger. It looks like a clown that kills people. Nightmare fuel.",
    14: "It’s a yellow tie. That’s it. It’s a tie that hangs from a tree and waits to die. Evolution gave up here.",
    15: "A bee with drills for hands. Because nature hates you and wants you to suffer. It stabs you for looking at it.",
    16: "The pigeon of the Pokémon world. It’s everywhere, it’s annoying, and it probably poops on your car.",
    17: "It’s Pidgey with a bad haircut. It thinks it’s tough, but it’s still just a bird. It listens to My Chemical Romance.",
    18: "A bird that flies at Mach 2. Which means it would technically explode if it hit a window. Physics is optional.",
    19: "A purple rat. It’s the reason you call an exterminator, not a Pokémon trainer. It bites your ankles.",
    20: "A rat on steroids. It looks like it gnaws on drywall for fun. It definitely has rabies.",
    21: "The bird you catch because you couldn't find a Pidgey. It’s angry and has a beak like a shiv.",
    22: "A bird with a long neck and a bad attitude. It looks like a vulture that got a makeover. It eats roadkill.",
    23: "It’s a snake. Spelled backwards, it’s 'Snake'. Creativity was not a priority here. It eats eggs whole.",
    24: "A cobra with a face on its chest. It’s trying to be scary, but it just looks like a bad tattoo.",
    25: "The corporate mascot. It’s an electric rat that refuses to get in the ball. Overrated and overexposed.",
    26: "The one Pikachu refuses to become because it doesn't want to pay taxes and get a real job. It’s actually stronger, but nobody cares.",
    27: "A brick with claws. It curls into a ball to hide from its problems, which is relatable.",
    28: "A hedgehog that went to a punk concert once and made it its entire personality. It spikes its hair with gel.",
    29: "A rabbit with poison spikes. It’s cute, but it will stab you if you hug it. A toxic relationship in Pokémon form.",
    30: "It’s blue and angry. It looks like a rabbit that’s been through a divorce. It eats rocks.",
    31: "A dinosaur rabbit mom. It has boobs and armor. Biology is confused. It protects its young with violence.",
    32: "The male version of the toxic rabbit. It has a horn to compensate for something. It breaks things.",
    33: "It’s purple and angry. It looks like a rabbit that listens to death metal. It breaks its own ears.",
    34: "A kaiju rabbit dad. It breaks things and probably drinks too much beer. It destroys houses for fun.",
    35: "A pink alien fairy. It comes from the moon, supposedly. It’s basically a space hippie that demands attention.",
    36: "It looks like a pillow that gained sentience. It hears everything, so don't talk trash about it. It knows your secrets.",
    37: "A fox with six tails. It’s cute, firey, and probably sheds everywhere. It’s high maintenance.",
    38: "A fox with nine tails. It’s majestic, but it holds grudges for 1000 years. Do not cross it or it will curse your bloodline.",
    39: "A balloon with eyes. It sings until you fall asleep and then draws on your face. A sociopath with a marker.",
    40: "A bigger balloon. Its fur is 'sublime', which is just a fancy way of saying expensive to groom. It feels like a luxury rug.",
    41: "A bat with no eyes. It screams at you in caves. It is the bane of every trainer's existence. Repel was invented for this.",
    42: "A bat with a mouth that is 90% of its body. It drinks blood. Sleep tight. It’s watching you.",
    43: "A weed with legs. It walks around at night screaming. It’s a plant that needs an exorcist.",
    44: "It drools nectar that smells like rotting garbage. It’s the smelly kid in class. Flies love it, you won't.",
    45: "A flower that smells like a corpse. It’s pretty, but you can’t bring it home to mom. It causes allergies.",
    46: "A crab with mushrooms growing on its back. It has a fungal infection and we’re supposed to fight with it.",
    47: "The mushroom took over. The bug is dead. It’s a zombie crab controlled by a fungus. The Last of Us: Pokémon Edition.",
    48: "A purple furball with eyes. It shoots lasers from its eyes, because why not. It’s a moth larva with a gun.",
    49: "A moth that scatters toxic dust. It’s a health hazard with wings. It leaves powder everywhere.",
    50: "A thumb with a nose. It lives underground. No one knows what the rest of it looks like, and maybe we don't want to.",
    51: "Three thumbs with noses. They move in unison, which is creepy. Are they attached? We'll never know.",
    52: "A cat with a coin on its head. It loves money. It’s the capitalist of the Pokémon world. Payday is its favorite day.",
    53: "A fancy cat. It’s snobby and will scratch your leather sofa just to spite you. It judges your outfit.",
    54: "A duck with a migraine. It explodes with psychic energy when its head hurts. Get this bird some Advil.",
    55: "A blue duck that swims fast. It’s confused why it’s not a Psychic type. We are too. It glows sometimes.",
    56: "A monkey that is always angry. It throws poop and punches things. It has anger management issues.",
    57: "A monkey that is so angry it literally dies if it stops being angry. It’s a heart attack waiting to happen.",
    58: "A puppy that breathes fire. It’s loyal, cute, and a massive fire hazard. Don't let it on the carpet.",
    59: "A big dog that runs fast. It’s majestic, but good luck feeding it. It runs 6,000 miles a day.",
    60: "A tadpole with a swirl on its stomach. That swirl is actually its intestines. Enjoy that fact.",
    61: "A bigger tadpole with hands. It can slap you now. The intestines are still visible. It sweats slime.",
    62: "A muscular frog. It looks like it hits the gym 8 days a week and drinks raw eggs. It punches water.",
    63: "It sleeps 18 hours a day and teleports away when you try to catch it. A flake. It has anxiety.",
    64: "It holds a spoon and has a mustache. It bends spoons with its mind. A parlor trick pony.",
    65: "It has two spoons and an IQ of 5000. It’s smarter than you and it knows it. It does your taxes.",
    66: "A grey child that lifts weights. It’s weirdly humanoid and unsettling. It wants to spot you.",
    67: "It wears a belt to keep its power in check. Or maybe its pants up. Who knows. It poses constantly.",
    68: "It has four arms. It can punch you four times at once. It helps with moving furniture, though.",
    69: "A plant that looks like a bell. It shoots acid. Don't put your finger in it. It eats flies.",
    70: "A bigger bell plant. It hangs from trees and eats bugs. It looks constantly surprised.",
    71: "A pitcher plant that eats large animals. It smells like honey but tastes like death. It dissolves prey alive.",
    72: "A jellyfish with angry eyes. It stings you at the beach. Everyone hates it. It floats aimlessly.",
    73: "A jellyfish with 80 tentacles. It’s a floating nightmare of stinging pain. It builds underwater castles.",
    74: "A rock with arms. It punches people. It’s simple, effective, and dumb as a rock.",
    75: "A boulder with four arms. It rolls down hills and crushes hikers. Nature's bowling ball.",
    76: "A turtle made of rocks. It explodes if you look at it wrong. A walking landmine.",
    77: "A horse on fire. Don't ride it unless you want third-degree burns on your inner thighs.",
    78: "A unicorn on fire. It runs fast and looks cool, but it’s still a fire hazard. It gallops at 150mph.",
    79: "A pink thing that is slow and dumb. It fishes with its tail and forgets what it’s doing. It feels pain 5 minutes late.",
    80: "The pink thing got bit on the butt by a shell and now it’s a genius? Evolution is weird. It walks upright now.",
    81: "A magnet with an eye. It sticks to your fridge and erases your credit cards. It floats on magnetism.",
    82: "Three magnets stuck together. The creativity budget ran out here. It causes blackouts.",
    83: "A duck holding a leek. It tastes delicious, apparently. It comes with its own garnish. It fights with a vegetable.",
    84: "A bird with two heads. They argue with each other. It’s a walking identity crisis. It runs fast.",
    85: "A bird with three heads. One represents joy, one sorrow, and one anger. It’s a mood swing with wings.",
    86: "A seal with a horn. It lives in ice. It’s cute but smells like fish. It claps for food.",
    87: "A dugong. It’s majestic and white. Sailors used to think these were mermaids. Sailors were lonely.",
    88: "A pile of purple sludge. It was created by pollution. Thanks, humanity. It smells like open sewage.",
    89: "A bigger pile of sludge. It smells so bad it kills plants just by existing. It shrinks in size as it smells worse.",
    90: "A clam with a tongue. It clamps onto things and never lets go. Like a needy ex. It swims backward.",
    91: "A clam with a spike. Its shell is harder than diamond. It’s basically a tank. It shoots spikes.",
    92: "A ball of gas with a face. It suffocates its prey. A literal toxic fart. It floats through walls.",
    93: "A ghost with disembodied hands. It licks you to steal your life force. Kinky? No, just deadly.",
    94: "A shadow with a smile. It hides in your shadow and waits to kill you. Sleep tight. It mimics you.",
    95: "A giant rock snake. It burrows underground at 50mph. It’s terrifyingly fast for a rock. It eats boulders.",
    96: "A tapir that eats dreams. If you have a nightmare, it’s because this thing didn't eat it. It hypnotizes you.",
    97: "It carries a pendulum and hypnotizes children. Stranger danger: The Pokémon. It kidnaps people.",
    98: "A crab. It has claws. It pinches. That’s about it. It walks sideways.",
    99: "A crab with one giant claw. It looks like it’s been working out only one arm. We know why.",
    100: "A ball that looks like a Poké Ball. It explodes. It’s a mimic that hates you. It rolls around.",
    101: "An upside-down ball. It explodes faster. It loves to self-destruct. It eats electricity.",
    102: "Six eggs. One of them is cracked and shows a brain. Are they seeds? Eggs? Who knows. They communicate telepathically.",
    103: "A walking palm tree with three faces. Each face has its own mind. A committee of idiots. It stomps around.",
    104: "It wears the skull of its dead mother. It cries at the moon. The most goth Pokémon ever. It throws bones.",
    105: "The orphan grew up and got a bone club. It’s aggressive and has abandonment issues. It headbutts things.",
    106: "A kickboxing blob with legs. It has no head, just eyes on its chest. Anatomy is optional. It stretches.",
    107: "A boxer in a dress. It punches faster than the eye can see. Don't make fun of the skirt. It needs a break.",
    108: "A pink blob with a giant tongue. It licks everything. It’s gross and sticky. It smells like saliva.",
    109: "A floating gas mine. It looks like a virus. It explodes if you get too close. It floats aimlessly.",
    110: "Two gas mines stuck together. One looks miserable. Being a conjoined twin made of poison sucks.",
    111: "A rock rhino. It has a tiny brain and runs in straight lines. It crashes into things constantly.",
    112: "A bipedal rock rhino. It can withstand lava. It’s tough but not smart. It spins its horn.",
    113: "An egg nurse. It carries an egg in a pouch. It’s basically a walking omelette station. It heals people.",
    114: "A vine monster with shoes. No one knows what it looks like under the vines. Probably disappointing.",
    115: "A mom kangaroo with a baby. The baby is never seen leaving the pouch. Failure to launch. It punches hard.",
    116: "A seahorse. It shoots ink. It’s cute and harmless unless you're a small shrimp. It swims upright.",
    117: "A spiky seahorse. It’s poisonous. Don't touch it. It sleeps in coral.",
    118: "A goldfish with a horn. It’s elegant but useless out of water. It swims in rivers.",
    119: "A fish with a horn. It’s slightly more aggressive. Still just a fish. It nests in waterfalls.",
    120: "A starfish with a jewel. It regenerates limbs. It’s an alien, probably. It communicates with radio waves.",
    121: "Two starfish glued together. It spins like a propeller and shoots water. It’s a geometric nightmare.",
    122: "A clown mime. It creates invisible walls. It’s creepy and hangs out with moms. It doesn't speak.",
    123: "A mantis with scythes for arms. It’s a ninja bug. It hates the color red. It slices prey.",
    124: "A lady in a dress that kisses people to freeze them. It speaks a language that sounds like human speech.",
    125: "A yellow electric tiger man. It spins its arms to generate power. It causes blackouts. It glows.",
    126: "A duck with a butt on its head. It lives in volcanoes. It’s made of fire. It spits flames.",
    127: "A stag beetle with a vice grip on its head. It breaks trees in half. It hates the cold. It wrestles.",
    128: "A bull with three tails. It whips itself to get angry. A masochist. It charges at everything.",
    129: "A useless fish. It splashes. It does nothing. It is a disappointment to its family. It jumps poorly.",
    130: "The useless fish got angry and became a sea dragon. It destroys cities for fun. It has a temper.",
    131: "A Loch Ness monster. It ferries people across the sea. It’s gentle and endangered. It sings.",
    132: "A purple blob. It can transform into anything. It’s used for... breeding. A lot. It smiles blankly.",
    133: "A generic dog/fox/cat thing. It has unstable DNA. It can become anything depending on the rock you throw at it.",
    134: "The water dog. It melts into water. It’s basically a puddle with ears. It has gills.",
    135: "The electric dog. It’s spiky and agitated. It’s like petting a live wire. It creates thunderstorms.",
    136: "The fire dog. It’s fluffy and warm. It stores heat in its body. A living hot water bottle.",
    137: "A digital duck. It’s made of code. It can enter cyberspace. Don't check its browser history.",
    138: "A fossil snail. It was resurrected from a rock. It has tentacles. Praise Helix. It bites.",
    139: "A spiky fossil snail. It has a beak that can crush bone. It’s a prehistoric nightmare. It died out for a reason.",
    140: "A fossil horseshoe crab. It has eyes on its back. It watches you while it sleeps. It scuttles.",
    141: "A fossil slasher. It has scythes for hands. It swims fast and cuts prey in half. It drinks fluids.",
    142: "A fossil pterodactyl. It flies and screams. It’s a dinosaur with an attitude. It eats while flying.",
    143: "A fat bear that sleeps and eats. It blocks roads. It is my spirit animal. It eats moldy food.",
    144: "An ice bird. It’s legendary and cold. It freezes moisture in the air to make snow. It’s elegant.",
    145: "An electric bird. It’s spiky and loud. It lives in thunderstorms. It drops lightning bolts.",
    146: "A fire bird. It’s on fire. It represents spring, apparently. It heals wounds with tears.",
    147: "A blue worm. It sheds its skin. It’s rare and hard to find. It grows slowly.",
    148: "A blue snake with wings on its head. It controls the weather. It’s elegant. It glows with aura.",
    149: "An orange dragon with tiny wings. It’s friendly and saves drowning sailors. The Moomin of dragons.",
    150: "A genetic experiment gone wrong. It hates humanity. It lives in a cave and broods. It’s overpowered.",
    151: "The ancestor of all Pokémon. It’s pink and floats. It hides under a truck. It giggles.",
    152: "A leaf dinosaur. It has a leaf on its head. It smells like herbs. It’s cute but weak.",
    153: "A bigger leaf dinosaur. It has a necklace of buds. It smells spicy. It’s getting tougher.",
    154: "A flower dinosaur. It breathes to revive dead grass. A walking air freshener. It basks in sunlight.",
    155: "A fire mouse. It has fire on its back. It’s timid but burns hot. It curls up to hide.",
    156: "A fire weasel. It has a mohawk of fire. It’s agile and burns things. It runs on two legs.",
    157: "A fire badger. It has a volcano on its neck. It rubs its fur together to cause explosions.",
    158: "A blue crocodile. It bites everything. It’s hyperactive. It dances when happy.",
    159: "A caveman crocodile. It wears a skin pattern like a toga. It’s getting older. It bites harder.",
    160: "A big blue alligator. It runs on two legs. It’s terrifyingly fast on land. It crushes rocks.",
    161: "A scout squirrel. It stands on its tail to look around. It’s paranoid. It stores berries.",
    162: "A long squirrel. It’s very long. It can corner like a drift car. It runs up trees.",
    163: "An owl with one leg. It has an internal clock. It’s always judging you. It hoots at night.",
    164: "A wise owl. It thinks deep thoughts. It’s smarter than your average bird. It flies silently.",
    165: "A ladybug with fists. It punches things. It’s surprisingly aggressive. It swarms.",
    166: "A ladybug alien. It uses starlight to power up. It’s a Power Ranger. It punches faster.",
    167: "A green spider with a face on its back. The face changes when it's angry. It traps prey.",
    168: "A red spider. It spins webs from its butt and its mouth. Efficient. It eats its prey alive.",
    169: "A bat with four wings. It flies silently. It bites you without you knowing. It drinks blood.",
    170: "A fish with a lightbulb. It lives in the deep sea. It zaps prey. It has glowing eyes.",
    171: "A dolphin with a lightbulb. It’s friendly but will electrocute you by accident. It swims deep.",
    172: "A baby Pikachu. It can't control its electricity and shocks itself. A liability. It’s cute though.",
    173: "A baby star. It looks like a marshmallow. It’s useless in battle. It drinks milk.",
    174: "A baby balloon. It bounces around. It has red eyes that stare into your soul. It sings softly.",
    175: "An egg with a head. It brings happiness, allegedly. It mostly just cries. It rolls around.",
    176: "A fairy egg. It flies with tiny wings. It spreads joy dust. It’s lucky.",
    177: "A tiny bird. It hops around. It can see the future but can't change it. It stares blankly.",
    178: "A totem pole bird. It sees the past and future simultaneously. It is paralyzed by existential dread.",
    179: "A sheep with static wool. It shocks you if you pet it. A forbidden pillow. It expands when charged.",
    180: "A pink sheep. It stands on two legs. Its wool is rubbery. It punches with electricity.",
    181: "A lighthouse dragon. It has a light on its tail. It guides ships and looks fabulous. It shears its own wool.",
    182: "A hula dancer flower. It dances in the sun. It smells nice but has no attacks. It hides in rain.",
    183: "A water mouse. Its tail is a float. It never drowns. It listens to water currents.",
    184: "A water rabbit. It has long ears. It plays in rivers and drowns unsuspecting swimmers. It’s deceptively strong.",
    185: "A rock that looks like a tree. It hates water. It’s a mimic that fails at mimicry. It cries fake tears.",
    186: "A green frog with a hair curl. It claps its hands and summons rain. A weather wizard. It leads Poliwags.",
    187: "A dandelion cat. It floats in the wind. It has no control over its life. It lands in puddles.",
    188: "A flower cat. It blooms in the sun. It’s happy as long as it’s warm. It sleeps a lot.",
    189: "A cotton ball cat. It rides the wind across the ocean. It spreads spores everywhere. It sneezes.",
    190: "A monkey with a hand on its tail. It’s mischievous and steals your keys. It laughs at you.",
    191: "A seed. It is the weakest Pokémon in existence. It falls from the sky and does nothing. It shakes.",
    192: "A sunflower. It moves its face to follow the sun. It’s creepy at night. It smiles forever.",
    193: "A dragonfly. It flies fast and sees everything. It’s a drone with wings. It creates sonic booms.",
    194: "A water axolotl. It has no arms. It smiles while it suffers. It lives in mud.",
    195: "A water salamander. It’s slippery and dumb. It bumps into rocks and doesn't care. It eats rocks.",
    196: "A psychic cat. It predicts the future by reading air currents. It’s elegant and judgmental.",
    197: "A dark cat. It glows in the dark. It sweats poison when it's agitated. Don't stress it out.",
    198: "A crow with a hat. It steals shiny things. It’s a mob boss. It brings gifts to friends.",
    199: "A slow hippo with a shell hat. It’s a genius now. It rules the beach. It gets bitten constantly.",
    200: "A ghost head. It screams to scare people. It feeds on fear. It pulls hair.",
    201: "Alphabet soup. There are 28 versions of this useless letter. Collect them all, or don't. They stick to walls.",
    202: "A blue blob with a tail. The tail is the real body. It hits itself to endure pain. It hides in caves.",
    203: "A giraffe with a tail that bites. The tail has a brain. It watches you while you sleep. It bites the head.",
    204: "A pinecone. It hangs from trees and explodes. It’s a grenade with eyes. It drops on people.",
    205: "A bagworm in a steel shell. It shoots spikes. It’s a fortress. It spins rapidly.",
    206: "A land snake with wings. It digs with its tail. It’s rare and weird. It flies backwards.",
    207: "A flying scorpion. It glides on the wind. It clamps onto your face. It has claws.",
    208: "A steel snake. It chews through mountains. Its teeth are harder than diamond. It polishes its body.",
    209: "A pink bulldog. It looks scary but is actually a coward. It runs away from chihuahuas. It growls softly.",
    210: "A purple bulldog. It’s timid but has a strong jaw. It’s a good guard dog if it doesn't faint.",
    211: "A pufferfish. It shoots toxic needles. It’s a floating mine. It swallows water to explode.",
    212: "A red metal mantis. It has claws that crush steel. It’s cooler than you. It moves too fast to see.",
    213: "A moldy rock turtle. It ferments berries in its shell. It makes moonshine. It gives juice to friends.",
    214: "A giant beetle. It flips tanks. It loves honey and fighting. It sleeps on trees.",
    215: "A weasel with claws. It steals eggs. It’s a thief and a vandal. It leaves ice trails.",
    216: "A teddy bear with a moon. It’s cute but licks honey off its paws which are soaked in it.",
    217: "A bear with a sun. It snaps trees in half. It’s angry and hungry. It hibernates.",
    218: "A lava slug. It never sleeps. If it stops moving, it hardens and dies. It’s hot to the touch.",
    219: "A lava snail. Its shell is made of hardened magma. It’s brittle. It falls apart.",
    220: "A pig with fur. It smells mushrooms. It’s a truffle pig. It digs constantly.",
    221: "A boar with fur. Its hair covers its eyes. It charges blindly. It has big tusks.",
    222: "A coral reef. It grows on its head. It sheds branches as gifts. It regenerates.",
    223: "A fish that looks like a gun. It shoots water with sniper accuracy. It clings to Mantine.",
    224: "An octopus tank. It shoots ink and rocks. It’s heavy artillery. It has suction cups.",
    225: "A Santa penguin. It gives presents that explode. It’s a troll. It carries food in its tail.",
    226: "A kite ray. It swims calmly. It lets fish clean its leftovers. It flies out of water.",
    227: "A steel bird. Its feathers are swords. It flies at 180mph. It nests in thorns.",
    228: "A dark dog. It hunts in packs. It uses teamwork to kill. It howls at dawn.",
    229: "A hellhound. Its fire burns forever. If you get burned, it hurts for life. It breathes toxins.",
    230: "A sea dragon. It creates whirlpools. It sleeps deep in the ocean. It yawns.",
    231: "A tiny elephant. It’s strong for its size. It plays in the mud. It uses its trunk as a shovel.",
    232: "A tire elephant. It rolls into a ball and flattens cars. It’s armor-plated. It charges downhill.",
    233: "A digital duck upgrade. It’s smoother and smarter. It explores space. It computes pi.",
    234: "A deer with an eye on its butt. It creates illusions. It stares into your soul. It spooks easily.",
    235: "A painter dog. It paints with its tail. Its art expresses its feelings. It marks territory.",
    236: "A fighting kid. It has potential to be three different things. No pressure. It trains daily.",
    237: "A spinning top man. It kicks while spinning. It gets dizzy. It drills into the ground.",
    238: "A kissing baby. It kisses everything. It’s weirdly affectionate. It leaves lip marks.",
    239: "A plug baby. It spins its arms to generate electricity. It’s a living generator. It loves storms.",
    240: "A fire baby. It spits embers. It’s a fire hazard in a diaper. It has a fever.",
    241: "A cow. It produces milk. It rolls around. It’s a tank. It drinks its own milk.",
    242: "A nurse egg. It has the highest HP. It takes hits and smiles. It throws eggs.",
    243: "A thunder tiger. It carries a storm on its back. It barks thunder. It runs on clouds.",
    244: "A volcano lion. It barks magma. It represents the pressure of the earth. It is stoic.",
    245: "A water leopard. It purifies water. It runs on the wind. It is elusive.",
    246: "A rock skin baby. It eats dirt to grow. It lives deep underground. It hates light.",
    247: "A rock shell. It’s waiting to evolve. It has a temper. It vents gas.",
    248: "A Godzilla. It destroys mountains. It is invincible. It has a sand stream.",
    249: "A sea guardian. It suppresses storms. It lives in a trench. It flies.",
    250: "A rainbow bird. It resurrects the dead. It flies continuously. It leaves rainbows.",
    251: "A forest fairy. It travels through time. It brings lush forests. It is protected.",
    252: "A gecko with a twig. It’s cool and collected. It climbs walls. It slams its tail.",
    253: "A gecko with leaves. It jumps fast. It’s agile. It has sharp leaves.",
    254: "A gecko with a tree on its tail. It grows seeds on its back. It’s a jungle warrior.",
    255: "A fire chick. It’s warm to hold. It has a fire inside. It follows its trainer.",
    256: "A fire chicken. It kicks things. It’s getting aggressive. It practices pecking.",
    257: "A fire fighting chicken. It jumps over buildings. It kicks with fire. It has strong legs.",
    258: "A mud fish. It has a fin on its head. It’s sturdy. It lifts rocks.",
    259: "A mud fish with legs. It plays in the mud. It’s happy. It stands up.",
    260: "A mud monster. It drags boulders. It swims faster than a jet ski. It senses storms.",
    261: "A dark dog. It bites everything. It’s tenacious. It chases moving things.",
    262: "A dark wolf. It hunts in packs. It obeys orders. It howls.",
    263: "A raccoon. It walks in zigzags. It’s curious. It picks up trash.",
    264: "A badger. It runs in straight lines. It tackles everything. It has obstacles.",
    265: "A worm. It eats leaves. It’s waiting to change. It has spikes.",
    266: "A white cocoon. It hangs from branches. It waits. It uses silk.",
    267: "A butterfly. It drinks nectar. It’s colorful. It attacks with wind.",
    268: "A purple cocoon. It’s hard. It waits. It spies.",
    269: "A moth. It scatters dust. It’s attracted to light. It fights with poison.",
    270: "A lily pad. It floats on water. It carries small Pokémon. It searches for clean water.",
    271: "A kappa. It plays pranks. It loves music. It pulls weeds.",
    272: "A pineapple duck. It dances to music. It’s always happy. It has rhythm.",
    273: "A acorn. It hangs from trees. It looks like a nut. It drops on heads.",
    274: "A leaf goblin. It plays a flute. It lives in forests. It hates noise.",
    275: "A leaf tengu. It creates wind storms. It guards forests. It has a long nose.",
    276: "A swallow. It’s brave. It stands up to big foes. It eats bugs.",
    277: "A big swallow. It dives at prey. It’s fast. It grooms its wings.",
    278: "A seagull. It carries food in its beak. It floats on updrafts. It nests on cliffs.",
    279: "A pelican. It carries things in its mouth. It’s a courier. It swallows whole.",
    280: "A feeling Pokémon. It senses emotions. It hides from negativity. It teleports.",
    281: "A dancer. It spins on tiptoes. It senses feelings. It dances when happy.",
    282: "A guardian angel. It protects its trainer. It creates black holes. It floats.",
    283: "A pond skater. It slides on water. It secretes oil. It jumps.",
    284: "A moth with eye patterns. It scares predators. It flies in rain. It uses antennas.",
    285: "A mushroom. It scatters spores. It’s grumpy. It eats compost.",
    286: "A boxing mushroom. It has stretchy arms. It punches fast. It has footwork.",
    287: "A sloth. It sleeps all day. It eats 3 leaves. It moves when necessary.",
    288: "A monkey. It can't sit still. It runs wild. It has adrenaline.",
    289: "A giant sloth. It’s lazy again. It hits like a truck. It lounges.",
    290: "A cicada nymph. It lives underground. It waits. It digs roots.",
    291: "A cicada. It moves fast. It buzzes loud. It leaves a shell.",
    292: "A ghost shell. It steals souls. Don't look in the hole. It floats behind you.",
    293: "A whisper. It cries loud. It hears everything. It stomps.",
    294: "A loud speaker. It shouts to attack. It has big ears. It creates shockwaves.",
    295: "A boombox. It creates earthquakes with sound. It roars. It opens its pipes.",
    296: "A sumo trainee. It trains hard. It eats a lot. It slaps its belly.",
    297: "A sumo master. It slaps hard. It stops trains. It has thick fat.",
    298: "A blue mouse. It bounces on its tail. It’s sad. It needs a hug.",
    299: "A nose compass. It always points north. It can't turn. It gets dizzy.",
    300: "A kitten. It chases its tail. It’s cute. It meows.",
    301: "A cat lady. It’s elegant. It hates dirt. It has a pillow.",
    302: "A gem eater. It has gems for eyes. It lives in caves. It eats diamonds.",
    303: "A mouth head. It deceives prey. It bites hard. It has a fake face.",
    304: "A metal eater. It eats iron ore. It makes armor. It digs tunnels.",
    305: "A metal beast. It eats trucks. It clashes for territory. It has a lair.",
    306: "A metal monster. It claims a mountain. It destroys environments. It is heavy.",
    307: "A meditator. It eats one berry a day. It floats. It trains mind.",
    308: "A yoga master. It senses auras. It dances in battle. It kicks.",
    309: "A static dog. It stores electricity in fur. It runs fast. It zaps.",
    310: "A lightning dog. It creates thunder clouds. It discharges power. It bites.",
    311: "A plus mouse. It cheers for friends. It sparks. It holds hands.",
    312: "A minus mouse. It cheers for partners. It sparks. It cries.",
    313: "A firefly. It uses light to signal. It loves sweet scents. It flashes.",
    314: "A firefly lady. It guides the swarm. It draws patterns. It smells nice.",
    315: "A rose lady. It has poison thorns. It smells sweet. It dances.",
    316: "A stomach. It eats everything. It digests scrap metal. It has no bones.",
    317: "A poison bag. It swallows things whole. It has no teeth. It oozes.",
    318: "A piranha. It has rough skin. It bites boats. It swarms.",
    319: "A shark torpedo. It swims fast. It breaks hulls. It chases.",
    320: "A ball whale. It bounces on beaches. It drinks tons of water. It splashes.",
    321: "A giant whale. It is the biggest. It eats schools of fish. It dives.",
    322: "A camel. It stores magma. It’s slow. It humps.",
    323: "A volcano camel. It erupts when angry. It has craters. It shakes.",
    324: "A coal turtle. It burns coal inside. It smokes. It digs.",
    325: "A spring pig. It bounces. If it stops, it dies. It has a pearl.",
    326: "A pig dancer. It controls pearls. It dances oddly. It uses psychic power.",
    327: "A dizzy bear. It has unique spots. It stumbles. It confuses foes.",
    328: "A pit digger. It waits in a hole. It has big jaws. It snaps.",
    329: "A dragon fly. It vibrates wings. It causes headaches. It flies.",
    330: "A desert spirit. It creates sandstorms. It sings. It flies.",
    331: "A cactus ball. It lives in deserts. It has a flower. It shakes.",
    332: "A scarecrow. It hunts at night. It stalks travelers. It stands still.",
    333: "A cotton bird. It likes to clean. It sits on heads. It is soft.",
    334: "A cloud bird. It sings soprano. It flies in clouds. It has cotton wings.",
    335: "A mongoose. It fights snakes. It has claws. It is angry.",
    336: "A snake. It fights mongooses. It has a knife tail. It bites.",
    337: "A moon rock. It floats. It glows at night. It stares.",
    338: "A sun rock. It spins. It glows in the day. It floats.",
    339: "A whisker fish. It senses quakes. It’s slimy. It hides.",
    340: "A catfish. It causes quakes. It eats anything. It is heavy.",
    341: "A crab. It was a pet. It adapted to the wild. It pinches.",
    342: "A rogue crab. It destroys ponds. It’s violent. It throws stars.",
    343: "A clay doll. It spins on one leg. It was made by ancients. It balances.",
    344: "A clay idol. It floats. It shoots beams. It rotates.",
    345: "A sea lily. It was extinct. It anchors to rocks. It waves.",
    346: "A barnacle plant. It melts prey. It lives in shallows. It waits.",
    347: "A shrimp fossil. It swims with wings. It has claws. It is fast.",
    348: "A armor shrimp. It has plate armor. It hunts on land. It slashes.",
    349: "A ugly fish. It eats anything. It’s hardy. It splashes.",
    350: "A beautiful serpent. It calms anger. It’s a muse. It glows.",
    351: "A weather ball. It changes with weather. It’s small. It floats.",
    352: "A chameleon. It blends in. It has a zigzag stripe. It creeps.",
    353: "A ghost doll. It feeds on envy. It seeks its owner. It cries.",
    354: "A zipper doll. It holds a grudge. It was thrown away. It zips.",
    355: "A skull ghost. It loves crying children. It passes through walls. It has one eye.",
    356: "A mummy ghost. It has a black hole inside. It waves its hands. It binds.",
    357: "A banana dinosaur. It flies with leaves. It gives fruit. It stomps.",
    358: "A wind chime. It floats in wind. It makes sounds. It heals.",
    359: "A disaster dog. It warns of danger. It is misunderstood. It has a horn.",
    360: "A patient blob. It endures attacks. It has a tail eye. It bounces.",
    361: "A snow hat. It shivers. It eats snow. It huddles.",
    362: "A hockey mask. It freezes moisture. It has a rock body. It glares.",
    363: "A seal ball. It rolls on ice. It claps. It eats fish.",
    364: "A seal. It balances balls. It has whiskers. It swims.",
    365: "A walrus. It breaks ice. It has thick blubber. It has tusks.",
    366: "A pearl clam. It lives in the deep. It makes pearls. It clamps.",
    367: "A eel. It lives in the deep. It hunts clams. It is pink.",
    368: "A fish. It has a map on its scales. It lives long. It swims deep.",
    369: "A rock map. It has no brain. It’s a living fossil. It eats rocks.",
    370: "A heart fish. It swims in schools. It jumps. It kisses.",
    371: "A dragon head. It wants to fly. It jumps off cliffs. It has a hard head.",
    372: "A shell dragon. It rolls fast. It protects its body. It waits.",
    373: "A salamence. It flies finally. It burns fields. It is happy.",
    374: "A robot eye. It floats. It calculates. It has magnetism.",
    375: "A robot crab. It has four legs. It thinks fast. It combines.",
    376: "A super computer. It has four legs. It rivals humans. It floats.",
    377: "A rock golem. It guards caves. It solves puzzles. It crumbles.",
    378: "A ice golem. It stays frozen. It breaks easily. It reforms.",
    379: "A steel golem. It is flexible. It is unknown metal. It stretches.",
    380: "A jet dragon. It flies fast. It has a sister. It is red.",
    381: "A jet dragon. It flies fast. It has a brother. It is blue.",
    382: "A rain god. It expands oceans. It sleeps. It has fins.",
    383: "A sun god. It expands land. It sleeps. It has spikes.",
    384: "A sky god. It stops fights. It lives in ozone. It is green.",
    385: "A wish maker. It sleeps 1000 years. It has an eye. It grants wishes.",
    386: "A virus alien. It changes forms. It attacks. It is from space.",
    387: "A turtle with a twig. It’s shy. It lives near lakes. It photosynthesizes.",
    388: "A bush turtle. It knows where springs are. It carries a shell. It bites.",
    389: "A continent turtle. It carries a small world. It doesn't move. It grows trees.",
    390: "A fire monkey. It climbs cliffs. It has a butt flame. It scratches.",
    391: "A fighting monkey. It has a long tail. It uses martial arts. It kicks.",
    392: "A monkey king. It has fire hair. It fights fast. It punches.",
    393: "A penguin. It’s proud. It hates being touched. It pecks.",
    394: "A prince penguin. It lives alone. It has strong wings. It slashes.",
    395: "A emperor penguin. It leads the pack. It swims fast. It has steel wings.",
    396: "A bird. It flies well. It mimics cries. It chatters.",
    397: "A hawk. It has claws. It grooms itself. It dives.",
    398: "A raptor. It has a crest. It intimidates. It fights.",
    399: "A beaver. It gnaws logs. It builds dams. It curls up.",
    400: "A worker beaver. It carries things. It’s dull. It swims.",
    401: "A cricket. It sings. It has a hard shell. It shakes.",
    402: "A violin cricket. It plays melodies. It uses knife arms. It conducts.",
    403: "A spark lion. It flashes light. It rivals others. It bites.",
    404: "A x-ray lion. It sees through walls. It hunts. It stalks.",
    405: "A x-ray lion king. It sees everything. It leads. It roars.",
    406: "A bud. It likes clean water. It is sensitive. It opens.",
    407: "A bouquet. It attracts prey. It has thorns. It dances.",
    408: "A fossil. It has a hard skull. It headbutts. It charges.",
    409: "A rampardos. It smashes things. It has a thick skull. It breaks.",
    410: "A shield fossil. It has a face shield. It protects. It blocks.",
    411: "A bastion. It blocks attacks. It is a wall. It stands.",
    412: "A bagworm. It makes a cloak. It evolves differently. It hides.",
    413: "A trash cloak. It uses trash. It adapts. It changes.",
    414: "A moth. It loves honey. It protects the hive. It flies.",
    415: "A bee queen. It commands the hive. It fights. It orders.",
    416: "A bee. It gathers honey. It serves the queen. It stings.",
    417: "A squirrel. It stores electricity. It runs fast. It climbs.",
    418: "A weasel. It floats. It has two tails. It swims.",
    419: "A float weasel. It rescues people. It swims fast. It dives.",
    420: "A cherry. It is small. It is tasty. It bounces.",
    421: "A flower. It opens in sun. It is positive. It smiles.",
    422: "A slug. It lives in mud. It is soft. It squishes.",
    423: "A sea slug. It has three heads. It lives in mud. It oozes.",
    424: "A monkey. It has a hand tail. It jumps. It grabs.",
    425: "A balloon. It drifts. It carries souls. It has no feet.",
    426: "A blimp. It carries people. It vanishes. It floats.",
    427: "A bunny. It has fluff. It kicks. It jumps.",
    428: "A lop bunny. It is elegant. It fights. It charms.",
    429: "A ghost. It screams. It scares people. It floats.",
    430: "A crow boss. It leads the flock. It is smart. It flies.",
    431: "A cat. It is sleek. It hypnotizes. It purrs.",
    432: "A fat cat. It is ugly. It binds prey. It squeezes.",
    433: "A bell. It rings. It floats. It chimes.",
    434: "A skunk. It smells. It sprays. It hisses.",
    435: "A tank skunk. It sprays far. It smells bad. It explodes.",
    436: "A mirror. It reflects. It is steel. It floats.",
    437: "A bell. It heals. It floats. It rings.",
    438: "A rock baby. It cries. It mimics. It throws rocks.",
    439: "A mime baby. It mimics. It is cute. It claps.",
    440: "A egg. It carries a stone. It is happy. It heals.",
    441: "A note. It mimics speech. It flies. It sings.",
    442: "A stone. It has a soul. It is forbidden. It spins.",
    443: "A land shark. It digs. It bites. It attacks.",
    444: "A shark. It flies. It hunts. It bites.",
    445: "A jet shark. It flies fast. It hunts. It slashes.",
    446: "A munchlax. It eats. It sleeps. It walks.",
    447: "A riolu. It senses aura. It runs. It punches.",
    448: "A lucario. It fights. It reads minds. It blasts.",
    449: "A hippo. It lives in sand. It sweats sand. It yawns.",
    450: "A hippo king. It is angry. It creates storms. It bites.",
    451: "A scorpion. It has claws. It poisons. It stings.",
    452: "A ogre scorpion. It crushes. It poisons. It grabs.",
    453: "A frog. It fights. It has poison sacs. It jabs.",
    454: "A toxic frog. It fights dirty. It stabs. It croaks.",
    455: "A plant. It eats bugs. It floats. It bites.",
    456: "A fish. It has fins. It glows. It swims.",
    457: "A neon fish. It glows deep. It swims. It flashes.",
    458: "A mantyke. It swims. It jumps. It glides.",
    459: "A tree. It creates snow. It is cold. It stands.",
    460: "A obama. It creates blizzards. It is big. It punches.",
    461: "A weavile. It hunts in packs. It is fast. It slashes.",
    462: "A magnet. It has three eyes. It floats. It zaps.",
    463: "A tongue. It licks. It is pink. It rolls.",
    464: "A rhyperior. It shoots rocks. It is heavy. It blasts.",
    465: "A vine. It grows arms. It grabs. It walks.",
    466: "A electivire. It punches. It shocks. It charges.",
    467: "A magmortar. It shoots fire. It burns. It blasts.",
    468: "A togekiss. It flies. It blesses. It smiles.",
    469: "A yanmega. It flies fast. It bites. It buzzes.",
    470: "A leafeon. It uses photosynthesis. It is calm. It sleeps.",
    471: "A glaceon. It freezes air. It is cold. It stares.",
    472: "A gliscor. It glides. It bites. It hangs.",
    473: "A mamoswine. It charges. It is ancient. It tusks.",
    474: "A porygon z. It glitches. It is weird. It floats.",
    475: "A gallade. It fights. It has blades. It slashes.",
    476: "A nosepass. It points north. It has a mustache. It floats.",
    477: "A dusknoir. It takes souls. It has a mouth. It floats.",
    478: "A froslass. It freezes prey. It is a ghost. It floats.",
    479: "A rotom. It possesses electronics. It pranks. It zaps.",
    480: "A uxie. It knows all. It sleeps. It floats.",
    481: "A mesprit. It feels all. It plays. It floats.",
    482: "A azelf. It wills all. It fights. It floats.",
    483: "A dialga. It controls time. It roars. It fights.",
    484: "A palkia. It controls space. It roars. It fights.",
    485: "A heatran. It crawls on ceilings. It melts. It burns.",
    486: "A regigigas. It pulls continents. It is slow. It stomps.",
    487: "A giratina. It lives in distortion. It is a ghost. It flies.",
    488: "A cresselia. It gives dreams. It flies. It heals.",
    489: "A phione. It drifts. It is rare. It swims.",
    490: "A manaphy. It bonds. It swims. It glows.",
    491: "A darkrai. It gives nightmares. It hides. It floats.",
    492: "A shaymin. It cleans air. It flies. It blooms.",
    493: "A arceus. It created all. It is god. It judges.",
    494: "A victini. It wins. It brings luck. It flies.",
    495: "A snivy. It is smug. It uses vines. It glares.",
    496: "A servine. It is fast. It uses vines. It slides.",
    497: "A serperior. It glares. It stops foes. It slides.",
    498: "A tepig. It shoots fire. It eats berries. It snorts.",
    499: "A pignite. It fights. It gets fat. It punches.",
    500: "A emboar. It has a beard of fire. It punches. It roars."
};
